version: '3.9'

services:
  compiler-explorer:
    image: chillibits/compiler-explorer:latest
    container_name: compiler-explorer
    restart: always
    ports:
      - 10240:10240
    environment:
      VIRTUAL_HOST: play.spicelang.com
      LETSENCRYPT_HOST: play.spicelang.com
      VIRTUAL_PORT: 10240
    networks:
      - nginx-proxy

  watchtower:
    image: containrrr/watchtower:latest
    container_name: compiler-explorer-watchtower
    restart: unless-stopped
    command:
      - --interval
      - "120"
    depends_on:
      compiler-explorer:
        condition: service_started
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true